routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group([
    'middleware' => ['verified'],
    'as' => 'admin.',
    'namespace' => 'Admin',
], function() {
    Route::group(['middleware' => ['auth'], 'prefix' => 'admin'], function() {
        Route::group(['middleware' => ['active']], function() {
            /*======================================= Dashboard ==============================================*/
            Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
            /*==================================== END Dashboard ==============================================*/

            /*======================================= Profile ==============================================*/
            Route::get('profile', 'ProfileController@myProfile')->name('profile');
            Route::patch('update-profile/{id}', 'ProfileController@updateProfile')->name('profile.update');
            Route::post('update-password', 'ProfileController@updatePassword')->name('profile.updatePassword');
            /*==================================== END Profile ==============================================*/

            /*======================================= User ==============================================*/
            Route::post('users/avatar', 'UserController@avatar')->name('users.avatar');
            Route::post('users/changeStatus', 'UserController@changeStatus')->name('users.changeStatus');
            Route::post('users/data', 'UserController@data')->name('users.data');
            Route::resource('users', 'UserController');
            /*==================================== END User ==============================================*/

            /*======================================= Role ==============================================*/
            Route::post('roles/data', 'RoleController@data')->name('roles.data');
            Route::resource('roles', 'RoleController');
            /*==================================== END Role ==============================================*/

            /*======================================= Work Experience ==============================================*/
            Route::post('work-experiences/data', 'WorkExperienceController@data')->name('workExperience.data');
            Route::resource('work-experiences', 'WorkExperienceController');
            /*==================================== END Work Experience ==============================================*/

            /*======================================= Organization ==============================================*/
            Route::post('organization/data', 'OrganizationController@data')->name('organization.data');
            Route::resource('organization', 'OrganizationController');
            /*==================================== END Organization ==============================================*/
        });
    });
});

Route::group(['as' => 'user.', 'namespace' => 'User'], function() {
    Route::get('user/set-password/{code}', 'RegisterController@setPassword')->name('register.setPassword');
    Route::post('user/update-password/{id}', 'RegisterController@updatePassword')->name('register.updatePassword');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*============================================= Change Language ================================================*/
Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    app()->setLocale($locale);
    return redirect()->back();
});
/*============================================= Change Language ================================================*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/verify-email', [\App\Http\Controllers\Auth\EmailVerificationPromptController::class, '__invoke'])
    ->middleware('auth')
    ->name('verification.notice');

Route::get('/verify-email/{id}/{hash}', [\App\Http\Controllers\Auth\VerifyEmailController::class, '__invoke'])
    ->middleware(['auth', 'signed', 'throttle:6,1'])
    ->name('verification.verify');

Route::post('/email/verification-notification', [\App\Http\Controllers\Auth\EmailVerificationNotificationController::class, 'store'])
    ->middleware(['auth', 'throttle:6,1'])
    ->name('verification.send');

app/Models/Role.php
<?php

namespace App\Models;

use Spatie\Permission\Models\Role as BaseRole;
use Spatie\Translatable\HasTranslations;

class Role extends BaseRole
{
    use HasTranslations;

    public static $status = [
        'active' => [
            'code' => 1,
            'slug' => 'active'
        ],
        'inactive' => [
            'code' => 0,
            'slug' => 'inactive'
        ]
    ];

    public static $filter_keys = [
        'status' => 'status',
        'module' => 'module',
//        'is_vendor' => 'is_vendor'
    ];

    public $translatable = ['display_name'];

    protected $casts = [
        'display_name' => 'array'
    ];

    /**
     * Get only active roles
     */
    public function scopeActive($query)
    {
        return $query->where('status', self::$status['active']['code']);
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Module;
use App\Http\Controllers\Controller;
use DataTables;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use App\Models\Role;
use App\Models\Permission;
use App\Models\User;

class RoleController extends Controller
{
    public function index()
    {
        $modules = Module::all()->mapWithKeys(function($value, $key) {
            return [translate($value->display_name) => $value->name];
        })->prepend('', trans('admin_lang.select_module'));

        $role_status = [trans('admin_lang.select_status') => ''];
        foreach (Role::$status as $key => $status) {
            $role_status[trans('admin_lang.status_'.$status['slug'])] = $status['code'];
        }

        $filters = [
            Role::$filter_keys['status'] => $role_status,
            Role::$filter_keys['module'] => $modules,
        ];
        return view('admin.roles.index', compact('filters'));
    }

    //ajax loading of data for datatables
    public function data(Request $request)
    {
        $roles = Role::with('permissions.module');
        //apply filters if available
        if ($request->has(Role::$filter_keys['status']) && $request[Role::$filter_keys['status']] != '') {
            $roles = $roles->where('status', $request[Role::$filter_keys['status']]);
        }

        if ($request->has(Role::$filter_keys['module']) && !empty($request[Role::$filter_keys['module']])) {
            $roles = $roles->whereHas('permissions.module', function($modules) use ($request) {
                $modules->where('name', strip_tags($request[Role::$filter_keys['module']]));
            });
        }
        $roles = $roles->withCount(['users'])->get();

        return DataTables::of($roles)
            ->rawColumns(['users', 'status'])
            ->addColumn('users', function($roles) {
                return '<a href="'.route('admin.users.index', [User::$filter_keys['role'] => $roles->name]).'">'.$roles->users_count.'</a>';
            })
            ->editColumn('display_name', function($roles) {
                return $roles->display_name;
            })
            ->addColumn('modules', function($roles) {
                $modules = Module::with('permissions');
                if (!$roles->permissions->pluck('name')->contains('*')) {
                    $modules = $modules->whereIn('id', $roles->permissions->groupBy('module_id')->keys());
                }
                $modules = $modules->get();
                return view('admin.roles.partials.modules', compact('roles', 'modules'));
            })
            ->editColumn('status', function($roles) {
                return view('admin.roles.partials.status', compact('roles'));
            })
            ->addColumn('action', function($roles) {
                return view('admin.roles.partials.actions', compact('roles'));
            })
            ->removeColumn(['name', 'guard_name', 'permissions', 'created_at', 'updated_at'])
            ->make(true);
    }

    public function create()
    {
        $permissions = Permission::select('id','name','module_id')->get()->groupBy('module.name');
        $modules = array_keys($permissions->toArray());
        return view('admin.roles.create', compact('modules','permissions'));
    }

    public function store(Request $request)
    {
        $this->__validate($request);

        try {
            $role = Role::create([
                'name' => $request->name,
                'display_name' => $request->display_name,
                'guard_name' => config('auth.defaults.guard'),
                'status' => $request->status ?? Role::$status['inactive']['code']
            ]);

            $permissions = $request->permissions;
            $role->givePermissionTo($permissions);
            session()->flash('success', trans('admin_lang.role_created'));
            return [
                'response' => config('response.success'),
                'redirect' => route('admin.roles.index')
            ];
        } catch (\Exception $e) {
            if (config('app.app_type') == 'local') {
                return [
                    'response' => config('response.error'),
                    'message' => $e->getMessage()
                ];
            }
            return [
                'response' => config('response.error'),
                'message' => trans('admin_lang.something')
            ];
        }
    }

    public function edit($role_id)
    {
        $role = Role::with('permissions')
            //->whereNotIn('name', array_merge(['admin'], auth()->user()->roles->pluck('name')->toArray()))
            ->findOrFail($role_id);

        $existingPermissions = $role->permissions->pluck('id')->toArray();
        $permissions = Permission::select('id','name','module_id')->get()->groupBy('module.name');
        $modules = array_keys($permissions->toArray());
        return view('admin.roles.edit', compact('role', 'modules','permissions','existingPermissions'));
    }

    public function update(Request $request, $role_id)
    {
        $role = Role::with('permissions')
            //->whereNotIn('name', array_merge(['admin'], auth()->user()->roles->pluck('name')->toArray()))
            ->findOrFail($role_id);
        $this->__validate($request, $role->id);

        try {
            $role->update([
                'display_name' => $request->display_name,
                'status' => $request->status ?? Role::$status['inactive']['code']
            ]);

            $permissions = $request->permissions;
            $role->syncPermissions($permissions);

            session()->flash('success', trans('admin_lang.role_updated'));
            return [
                'response' => config('response.success'),
                'redirect' => route('admin.roles.index')
            ];
        } catch (\Exception $e) {
            if (config('app.app_type') == 'local') {
                return [
                    'response' => config('response.error'),
                    'message' => $e->getMessage()
                ];
            }
            return [
                'response' => config('response.error'),
                'message' => trans('admin_lang.something')
            ];
        }
    }

    /**
     * @param Request $request
     * @param bool $is_update
     * @return array
     * @throws \Illuminate\Validation\ValidationException
     */
    private function __validate(Request $request, $is_update = false)
    {
        $request->merge(['name' => Str::slug($request->name)]);

        $unique_rule = 'unique:roles,name';
        if ($is_update) {
            $request->merge(['name' => '-']);
            $unique_rule .= ','.$is_update;
        }

        return $this->validate($request, [
            'name' => 'required|max:255|alpha_dash|'.$unique_rule,
            'display_name.*' => 'required|max:255',
            'status' => 'boolean',
        ]);
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.admin_main')

@section('title', trans('admin_lang.roles'))

@section('content')

    @include('components.breadcrumb',[
        'home_url' => route('admin.dashboard.index'),
        'links' => [
            [
                'url' => route('admin.roles.index'),
                'title' => trans('admin_lang.rolesManagement'),
            ]
        ],
        'current_page_title' => trans('admin_lang.create_role')
    ])
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="kt-portlet">
                    @include('components.header',['title' => trans('admin_lang.create_new_role'), 'icon' => 'fa fa-user-tie'])
                    <!--begin::Form-->
                    <form class="kt-form" action="{{ route('admin.roles.store') }}" method="POST">
                        <div class="kt-portlet__body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="name" class="required">@lang('admin_lang.name')</label>
                                        <input type="text" name="name" id="name" placeholder="{{ trans('admin_lang.role_name_placeholder') }}" required class="form-control">
                                    </div>
                                </div>
                                @foreach (config('countries') as $lang => $country)
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="display-name-{{ $lang }}" class="required">@lang('admin_lang.display_name') ({{ ucfirst($lang) }})</label>
                                        <input type="text" name="display_name[{{ $lang }}]" id="display_name-{{ $lang }}" placeholder="{{ trans('admin_lang.role_display_name_placeholder') }}" required class="form-control">
                                    </div>
                                </div>
                                @endforeach
                                <div class="col-lg-2">
                                    <div class="form-group">
                                        <div class="d-flex align-items-center">
                                            <label for="status">@lang('admin_lang.status')</label>
                                            <span class="kt-switch kt-switch--outline kt-switch--icon kt-switch--info ml-auto">
                                                <label>
                                                    <input type="checkbox" checked="checked" id="status" value="1" name="status" required>
                                                    <span></span>
                                                </label>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-1"></div>
                            </div>

                            <label for="modules" style="color: #48465B;font-weight: 500;margin-bottom: 20px;">@lang('admin_lang.give_permission_label')</label>

                            <div class="form-group row">
                                <div class="col-12">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th style="width: 17%;">
                                                <a class="permission-select-all" href="javascript:void(0);">@lang('admin_lang.str_select_all')</a>
                                                |
                                                <a class="permission-deselect-all" href="javascript:void(0);">@lang('admin_lang.str_deselect_all')</a>
                                            </th>
                                            <th class="text-center">@lang('admin_lang.str_read')</th>
                                            <th class="text-center">@lang('admin_lang.str_add')</th>
                                            <th class="text-center">@lang('admin_lang.str_edit')</th>
                                            <th class="text-center">@lang('admin_lang.str_delete')</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($modules as $module)
                                            <tr>
                                                <td>@lang('admin_lang.module_'.$module)</td>
                                                @foreach($permissions[$module] as $permission)
                                                    <td class="text-center">
                                                        <label class="checkbox">
                                                            <input type="checkbox" name="permissions[]" value="{{ $permission->id }}" title="{{ $permission->name }}">
                                                            <span></span>
                                                        </label>
                                                    </td>
                                                @endforeach
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                        <div class="kt-portlet__foot">
                            <div class="kt-form__actions">
                                @include('components.button',['type' => 'submit'])
                                @include('components.button',['type' => 'cancel', 'url' => route('admin.roles.index')])
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $('document').ready(function () {
            $('.permission-select-all').on('click', function(){
                $('.table').find("input[type='checkbox']").prop('checked', true);
            });

            $('.permission-deselect-all').on('click', function(){
                $('.table').find("input[type='checkbox']").prop('checked', false);
                return false;
            });
        });
    </script>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.admin_main')

@section('title', trans('admin_lang.roles'))

@section('content')
    @include('components.breadcrumb',[
        'home_url' => route('admin.dashboard.index'),
        'links' => [
            [
                'url' => route('admin.roles.index'),
                'title' => trans('admin_lang.rolesManagement'),
            ]
        ],
        'current_page_title' => trans('admin_lang.edit_role')
    ])
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="kt-portlet">
                    @include('components.header',['title' => trans('admin_lang.update_role'), 'icon' => 'fa fa-user-tie'])
                    <!--begin::Form-->
                    <form class="kt-form" action="{{ route('admin.roles.update', $role->id) }}" method="PATCH">
                        <div class="kt-portlet__body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="display_name" class="required">@lang('admin_lang.display_name')</label>
                                        <input type="text" name="display_name[en]" value="{{ $role->getTranslation('display_name', 'en') }}" id="display_name" placeholder="{{ trans('admin_lang.role_display_name_placeholder') }}" required class="form-control">
                                    </div>
                                </div>
                                <div class="col-lg-2">
                                    <div class="form-group">
                                        <div class="d-flex align-items-center">
                                            <label for="status">@lang('admin_lang.status')</label>
                                            <span class="kt-switch kt-switch--outline kt-switch--icon kt-switch--info ml-auto">
                                                <label>
                                                    <input type="checkbox" {{ $role->status ? 'checked' : '' }} id="status" value="1" name="status" required>
                                                    <span></span>
                                                </label>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-1"></div>
                            </div>

                            <label for="modules">@lang('admin_lang.give_permission_label')</label>

                            <div class="form-group row">
                                <div class="col-12">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th style="width: 17%;">
                                                <a class="permission-select-all" href="javascript:void(0);">@lang('admin_lang.str_select_all')</a>
                                                |
                                                <a class="permission-deselect-all" href="javascript:void(0);">@lang('admin_lang.str_deselect_all')</a>
                                            </th>
                                            <th class="text-center">@lang('admin_lang.str_read')</th>
                                            <th class="text-center">@lang('admin_lang.str_add')</th>
                                            <th class="text-center">@lang('admin_lang.str_edit')</th>
                                            <th class="text-center">@lang('admin_lang.str_delete')</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($modules as $module)
                                            <tr>
                                                <td>@lang('admin_lang.module_'.$module)</td>
                                                @foreach($permissions[$module] as $permission)
                                                    <td class="text-center">
                                                        <label class="checkbox">
                                                            <input type="checkbox" name="permissions[]" value="{{ $permission->id }}" @if(in_array($permission->id, $existingPermissions)) checked @endif title="{{ $permission->name }}">
                                                            <span></span>
                                                        </label>
                                                    </td>
                                                @endforeach
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="kt-portlet__foot">
                            <div class="kt-form__actions">
                                @include('components.button',['type' => 'update'])
                                @include('components.button',['type' => 'cancel', 'url' => route('admin.roles.index')])
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $('document').ready(function () {
            $('.permission-select-all').on('click', function(){
                $('.table').find("input[type='checkbox']").prop('checked', true);
            });

            $('.permission-deselect-all').on('click', function(){
                $('.table').find("input[type='checkbox']").prop('checked', false);
                return false;
            });
        });
    </script>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.admin_main')

@section('title', trans('admin_lang.roles'))

@push('styles')
<link rel="stylesheet" href="{{ asset('assets/css/dataTables.bootstrap4.min.css') }}">
@endpush

@section('content')
    <div class="kt-portlet kt-portlet--mobile">
        @include('components.header',['title' => trans('admin_lang.rolesManagement'), 'icon' => 'fa fa-user-tie'])
        <div class="kt-portlet__body">
            <div class="table_container">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered" id="roles-table">
                        <thead>
                            <tr>
                                <th>@lang('admin_lang.id')</th>
                                <th>@lang('admin_lang.title')</th>
                                <th>@lang('admin_lang.users')</th>
                                <th>@lang('admin_lang.modules')</th>
                                <th>@lang('admin_lang.status')</th>
                                <th>@lang('admin_lang.actions')</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
<script type="text/template" id="header-buttons">
{{--    @include('components.button',['type' => 'create', 'label' => trans('admin_lang.create_new_role'), 'url' => route('admin.roles.create')])--}}
</script>

<script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/js/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
    const url = "{{ route('admin.roles.data') }}";
    const lang = "{{ app()->getLocale() }}";
    const filters = {!! json_encode($filters) !!};

    jQuery(document).ready(function() {
        dataTable(jQuery('#roles-table'), url, [
                { data: 'index', defaultContent: '' },
                { data: 'display_name', name: 'display_name' },
                { data: 'users', name: 'users', searchable: false, orderable: false },
                { data: 'modules', name: 'modules', searchable: false, orderable: false },
                { data: 'status', name: 'status', orderable: true, searchable: false },
                { data: 'action', name: 'action', orderable: false, searchable: false }
            ],
            lang,
            filters,
            jQuery('#header-buttons').html()
        );
    });
</script>
@endpush