routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group([
    'middleware' => ['verified'],
    'as' => 'admin.',
    'namespace' => 'Admin',
], function() {
    Route::group(['middleware' => ['auth'], 'prefix' => 'admin'], function() {
        Route::group(['middleware' => ['active']], function() {
            /*======================================= Dashboard ==============================================*/
            Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
            /*==================================== END Dashboard ==============================================*/

            /*======================================= Profile ==============================================*/
            Route::get('profile', 'ProfileController@myProfile')->name('profile');
            Route::patch('update-profile/{id}', 'ProfileController@updateProfile')->name('profile.update');
            Route::post('update-password', 'ProfileController@updatePassword')->name('profile.updatePassword');
            /*==================================== END Profile ==============================================*/

            /*======================================= User ==============================================*/
            Route::post('users/avatar', 'UserController@avatar')->name('users.avatar');
            Route::post('users/changeStatus', 'UserController@changeStatus')->name('users.changeStatus');
            Route::post('users/data', 'UserController@data')->name('users.data');
            Route::resource('users', 'UserController');
            /*==================================== END User ==============================================*/

            /*======================================= Role ==============================================*/
            Route::post('roles/data', 'RoleController@data')->name('roles.data');
            Route::resource('roles', 'RoleController');
            /*==================================== END Role ==============================================*/

            /*======================================= Work Experience ==============================================*/
            Route::post('work-experiences/data', 'WorkExperienceController@data')->name('workExperience.data');
            Route::resource('work-experiences', 'WorkExperienceController');
            /*==================================== END Work Experience ==============================================*/

            /*======================================= Organization ==============================================*/
            Route::post('organization/data', 'OrganizationController@data')->name('organization.data');
            Route::resource('organization', 'OrganizationController');
            /*==================================== END Organization ==============================================*/
        });
    });
});

Route::group(['as' => 'user.', 'namespace' => 'User'], function() {
    Route::get('user/set-password/{code}', 'RegisterController@setPassword')->name('register.setPassword');
    Route::post('user/update-password/{id}', 'RegisterController@updatePassword')->name('register.updatePassword');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*============================================= Change Language ================================================*/
Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    app()->setLocale($locale);
    return redirect()->back();
});
/*============================================= Change Language ================================================*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/verify-email', [\App\Http\Controllers\Auth\EmailVerificationPromptController::class, '__invoke'])
    ->middleware('auth')
    ->name('verification.notice');

Route::get('/verify-email/{id}/{hash}', [\App\Http\Controllers\Auth\VerifyEmailController::class, '__invoke'])
    ->middleware(['auth', 'signed', 'throttle:6,1'])
    ->name('verification.verify');

Route::post('/email/verification-notification', [\App\Http\Controllers\Auth\EmailVerificationNotificationController::class, 'store'])
    ->middleware(['auth', 'throttle:6,1'])
    ->name('verification.send');

app/Models/Models/WorkExperience.php
<?php

namespace App\Models\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class WorkExperience extends Model
{
    use HasFactory;

    CONST WORD_COUNT = 300, WORKING_IN_SAME = 1;

    protected $guarded = ['id'];

    protected $dates = [
        'start_date',
        'end_date',
        'created_at',
    ];

}

app/Http/Controllers/Admin/WorkExperienceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Models\WorkExperience;
use App\Rules\MaxWordsRule;
use App\Traits\WorkExperienceDateCheck;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class WorkExperienceController extends Controller
{
    use WorkExperienceDateCheck;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.work_experience.index');
    }

    //Ajax loading of data for datatables
    public function data(Request $request)
    {
        $workExperience = WorkExperience::where('user_id', Auth::id());

        return DataTables::of($workExperience)
            ->editColumn('company_name', function ($workExperience) {
                return $workExperience->company_name;
            })
            ->editColumn('title', function ($workExperience) {
                return $workExperience->title;
            })
            ->editColumn('start_date', function ($workExperience) {
                return $workExperience->start_date->translatedFormat(config('defaults.time_format'));
            })
            ->editColumn('end_date', function ($workExperience) {
                return $workExperience->end_date ? $workExperience->end_date->translatedFormat(config('defaults.time_format')) : 'Present';
            })
            ->addColumn('created', function ($workExperience) {
                return $workExperience->created_at;
            })
            ->addColumn('action', function ($workExperience) {
                return view('admin.work_experience.partials.actions', compact('workExperience'));
            })
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.work_experience.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->__validate($request);
        try {
            $checkDateValidate = $this->dateValidate($request);

            if ($checkDateValidate['status'] == false) {
                session()->flash('error', $checkDateValidate['message']);
                return response()->json([
                    'status' => false,
                    'response' => config('response.error'),
                    'message' => $checkDateValidate['message'],
                ]);
            }

            DB::beginTransaction();
            $request['user_id'] = Auth::id();

            $request['start_date'] = Carbon::parse($request->start_date)->format('Y-m-d');
            $request['end_date'] = $request->end_date == null ? null : Carbon::parse($request->end_date)->format('Y-m-d');

            WorkExperience::create($request->only(
                'user_id', 'company_name', 'title', 'start_date', 'end_date', 'description','is_same_role'
            ));

            DB::commit();
            session()->flash('success', trans('admin_lang.work_experience_created'));
            return [
                'response' => config('response.success'),
                'redirect' => route('admin.work-experiences.index')
            ];
        } catch (\Exception $e) {
            DB::rollback();
            if (config('app.app_type') == 'local') {
                return [
                    'response' => config('response.error'),
                    'message' => $e->getMessage(),
                    'error' => $e->getMessage()
                ];
            }
            return [
                'response' => config('response.error'),
                'message' => trans('admin_lang.something'),
            ];
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $workExperience = WorkExperience::findOrFail($id);

        return view('admin.work_experience.edit', with([
            'workExperience' => $workExperience,
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $workExperience = WorkExperience::findOrFail($id);

        $this->__validate($request, $workExperience->id);

        try {
            $checkDateValidate = $this->dateValidate($request);

            if ($checkDateValidate['status'] == false) {
                session()->flash('error', $checkDateValidate['message']);
                return response()->json([
                    'status' => false,
                    'response' => config('response.error'),
                    'message' => $checkDateValidate['message'],
                ]);
            }

            $request['start_date'] = Carbon::parse($request->start_date)->format('Y-m-d');
            $request['end_date'] = Carbon::parse($request->end_date)->format('Y-m-d');

            $workExperience->update([
                'company_name' => $request->company_name,
                'title' => $request->title,
                'start_date' => $request->start_date,
                'end_date' => $request->is_same_role == WorkExperience::WORKING_IN_SAME ? null : $request->end_date,
                'description' => $request->description,
                'is_same_role' => $request->is_same_role,
            ]);

            session()->flash('success', trans('admin_lang.work_experience_updated'));
            return [
                'response' => config('response.success'),
                'redirect' => route('admin.work-experiences.index')
            ];
        } catch (\Exception $e) {
            if (config('app.app_type') == 'local') {
                return [
                    'response' => config('response.error'),
                    'message' => $e->getMessage()
                ];
            }
            return [
                'response' => config('response.error'),
                'message' => trans('admin_lang.something')
            ];
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $workExperience = WorkExperience::findOrFail($id);
            $workExperience->delete();
            return [
                'response' => config('response.success'),
                'title' => trans('admin_lang.success'),
                'message' => trans('admin_lang.user_deleted'),
                'reload' => true
            ];
        } catch (\Exception $e) {
            if (config('app.app_type') == 'local') {
                return [
                    'response' => config('response.error'),
                    'title' => trans('admin_lang.error'),
                    'message' => $e->getMessage()
                ];
            }
            return [
                'response' => config('response.error'),
                'title' => trans('admin_lang.error'),
                'message' => trans('admin_lang.something')
            ];
        }
    }

    /**
     * @param Request $request
     * @param bool $is_update
     * @return array
     * @throws \Illuminate\Validation\ValidationException
     */
    private function __validate(Request $request)
    {
        $rules = [
            'company_name' => 'required|max:255',
            'title' => 'required|max:255',
            'start_date' => 'required',
            'end_date' => 'required_if:is_same_role,==,0',
            'description' => new MaxWordsRule(),
        ];

        $msg = [
            'end_date.required_if' => 'End date is required'
        ];

        return $this->validate($request, $rules, $msg);
    }
}

resources/views/admin/work_experience/create.blade.php
@extends('layouts.admin_main')

@section('title', trans('admin_lang.create_new_work_experience'))

@section('content')
    <!-- begin:: Subheader -->
    @include('components.breadcrumb',[
        'home_url' => route('admin.dashboard.index'),
        'links' => [
            [
                'url' => route('admin.work-experiences.index'),
                'title' => trans('admin_lang.work_experience_management'),
            ]
        ],
        'current_page_title' => trans('admin_lang.work_experience_create')
    ])
    <!-- end:: Subheader -->
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="kt-portlet">
                    @include('components.header',['title' => trans('admin_lang.create_new_work_experience'), 'icon' => 'fas fa-hotel'])
                    <!--begin::Form-->
                    <form class="kt-form" action="{{ route('admin.work-experiences.store') }}" method="POST">
                        <input type="hidden" id="is_same_role" name="is_same_role" value="0">
                        <div class="kt-portlet__body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="company_name" class="required">@lang('admin_lang.company_name')</label>
                                        <input id="company_name" type="text" name="company_name" placeholder="{{ trans('admin_lang.company_name_placeholder') }}" required class="form-control">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="title" class="required">@lang('admin_lang.title')</label>
                                        <input id="title" type="text" name="title" placeholder="{{ trans('admin_lang.title_or_role_placeholder') }}" required class="form-control">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="start_date" class="required">@lang('admin_lang.start_date')</label>
                                        <div class="input-group date">
                                            <input type="text" class="form-control datepicker" id="start_date" name="start_date" readonly  placeholder="{{ trans('admin_lang.start_date_placeholder') }}"/>
                                            <div class="input-group-append">
                                                <span class="input-group-text">
                                                    <i class="la la-calendar-check-o"></i>
                                                </span>
                                            </div>
                                        </div>
                                        <label class="checkbox">
                                            <input type="checkbox" id="is_same_role_checkbox" name="is_same_role_checkbox" value="0" title="{{ trans('admin_lang.same_role') }}" style="margin-top: 10px;">
                                            <span>{{ trans('admin_lang.same_role') }}</span>
                                        </label>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group" id="end_date_div">
                                        <label for="end_date" class="required">@lang('admin_lang.end_date')</label>
                                        <div class="input-group date">
                                            <input type="text" class="form-control datepicker" id="end_date" name="end_date" readonly  placeholder="{{ trans('admin_lang.end_date_placeholder') }}"/>
                                            <div class="input-group-append">
                                                <span class="input-group-text">
                                                    <i class="la la-calendar-check-o"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="description">@lang('admin_lang.description')</label>
                                        <textarea id="description" name="description" placeholder="{{ trans('admin_lang.description_placeholder') }}" required class="form-control"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="kt-portlet__foot">
                            <div class="kt-form__actions">
                                @include('components.button',['type' => 'submit'])
                                @include('components.button',['type' => 'cancel', 'url' => route('admin.work-experiences.index')])
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
@endsection

@push("scripts")
    <script src="{{ asset('assets/js/pages/crud/forms/widgets/bootstrap-datepicker.js') }}"></script>
    {{--<script src="{{ asset('assets/js/pages/crud/forms/widgets/form-repeater.js') }}"></script>--}}
    <script>
        $('.datepicker').datepicker({
            format : 'dd-mm-yyyy'
        });
        $(document).ready(function() {
            $('#is_same_role_checkbox').change(function() {
                if($("#is_same_role_checkbox").prop('checked') == true){
                    $('#end_date').val('');
                    $('#is_same_role_checkbox').val(1);
                    $('#is_same_role').val(1);
                    $('#end_date_div').addClass('d-none');
                }
                else{
                    $('#is_same_role_checkbox').val(0);
                    $('#is_same_role').val(0);
                    $('#end_date_div').removeClass('d-none');
                }
            });
        });
    </script>
@endpush

resources/views/admin/work_experience/edit.blade.php
@extends('layouts.admin_main')

@section('title', trans('admin_lang.work_experience'))

@section('content')
    @include('components.breadcrumb',[
        'home_url' => route('admin.dashboard.index'),
        'links' => [
            [
                'url' => route('admin.work-experiences.index'),
                'title' => trans('admin_lang.work_experience_management'),
            ]
        ],
        'current_page_title' => trans('admin_lang.work_experience_edit')
        ])
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="kt-portlet">
                    @include('components.header',['title' => trans(('admin_lang.update_work_experience')), 'icon' => 'fas fa-hotel'])
                    <!--begin::Form-->
                    <form class="kt-form" action="{{ route('admin.work-experiences.update', $workExperience->id) }}" method="PATCH">
                        <input type="hidden" id="is_same_role" name="is_same_role" value="{{ $workExperience->is_same_role }}">
                        <div class="kt-portlet__body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="company_name" class="required">@lang('admin_lang.company_name')</label>
                                        <input id="company_name" type="text" name="company_name" placeholder="{{ trans('admin_lang.company_name_placeholder') }}" required class="form-control" value="{{ $workExperience->company_name }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="title" class="required">@lang('admin_lang.title')</label>
                                        <input id="title" type="text" name="title" placeholder="{{ trans('admin_lang.title_or_role_placeholder') }}" required class="form-control" value="{{ $workExperience->title }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="start_date" class="required">@lang('admin_lang.start_date')</label>
                                        <div class="input-group date">
                                            <input type="text" class="form-control datepicker" id="start_date" name="start_date" readonly  placeholder="{{ trans('admin_lang.start_date_placeholder') }}" value="{{ \Carbon\Carbon::parse($workExperience->start_date)->format('d-m-Y') }}">
                                            <div class="input-group-append">
                                                <span class="input-group-text">
                                                    <i class="la la-calendar-check-o"></i>
                                                </span>
                                            </div>
                                        </div>
                                        <label class="checkbox">
                                            <input type="checkbox" id="is_same_role_checkbox" name="is_same_role_checkbox" value="{{ $workExperience->is_same_role }}" {{ $workExperience->is_same_role == \App\Models\Models\WorkExperience::WORKING_IN_SAME ? 'checked' : '' }} title="{{ trans('admin_lang.same_role') }}" style="margin-top: 10px;">
                                            <span>{{ trans('admin_lang.same_role') }}</span>
                                        </label>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group {{ $workExperience->is_same_role == \App\Models\Models\WorkExperience::WORKING_IN_SAME ? 'd-none' : '' }}" id="end_date_div">
                                        <label for="end_date" class="required">@lang('admin_lang.end_date')</label>
                                        <div class="input-group date">
                                            <input type="text" class="form-control datepicker" id="end_date" name="end_date" readonly  placeholder="{{ trans('admin_lang.end_date_placeholder') }}" value="{{ $workExperience->end_date != null ? \Carbon\Carbon::parse($workExperience->end_date)->format('d-m-Y') : '' }}">
                                            <div class="input-group-append">
                                                <span class="input-group-text">
                                                    <i class="la la-calendar-check-o"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="description">@lang('admin_lang.description')</label>
                                        <textarea id="description" name="description" placeholder="{{ trans('admin_lang.description_placeholder') }}" required class="form-control">{{ $workExperience->description }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="kt-portlet__foot">
                            <div class="kt-form__actions">
                                @include('components.button',['type' => 'update'])
                                @include('components.button',['type' => 'cancel', 'url' => route('admin.work-experiences.index')])
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
@endsection

@push("scripts")
    <script src="{{ asset('assets/js/pages/crud/forms/widgets/bootstrap-datepicker.js') }}"></script>
    <script>
        $('.datepicker').datepicker({
            format : 'dd-mm-yyyy'
        });
        $(document).ready(function() {

            $('#is_same_role_checkbox').change(function() {

                if($("#is_same_role_checkbox").prop('checked') == true){
                    $('#end_date').val('');
                    $('#end_date_div').addClass('d-none');
                    $('#is_same_role_checkbox').val(1);
                    $('#is_same_role').val(1);
                }
                else{
                    $('#is_same_role_checkbox').val(0);
                    $('#is_same_role').val(0);
                    $('#end_date_div').removeClass('d-none');
                }

            });
        });
    </script>
@endpush

resources/views/admin/work_experience/index.blade.php
@extends('layouts.admin_main')

@section('title')
    @lang('admin_lang.work_experience_management')
@endsection

@push('styles')
<link rel="stylesheet" href="{{ asset('assets/css/dataTables.bootstrap4.min.css') }}">
@endpush

@section('content')
    <div class="kt-portlet kt-portlet--mobile">
        @include('components.header',['title' => trans('admin_lang.work_experience_management'), 'icon' => 'fas fa-hotel'])
        <div class="kt-portlet__body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered" id="work-experience-table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>@lang('admin_lang.company_name')</th>
                        <th>@lang('admin_lang.title_or_role')</th>
                        <th>@lang('admin_lang.start_date')</th>
                        <th>@lang('admin_lang.end_date')</th>
                        <th>@lang('admin_lang.created_at')</th>
                        <th>@lang('admin_lang.actions')</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script type="text/template" id="header-buttons">
    @include('components.button',['type' => 'create', 'label' => trans('admin_lang.create_new_work_experience'), 'url' => route('admin.work-experiences.create')])
</script>

<script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/js/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        dataTable(jQuery('#work-experience-table'), "{{ route('admin.workExperience.data') }}", [
                { data: 'index', defaultContent: '', orderable: false, searchable: false },
                { data: 'company_name', name: 'company_name', searchable: true, orderable: true },
                { data: 'title', name: 'title', searchable: true, orderable: true },
                { data: 'start_date', name: 'start_date', searchable: false, orderable: true  },
                { data: 'end_date', name: 'end_date', searchable: false, orderable: true  },
                { data: 'created', name: 'created_at', searchable: false, orderable: true  },
                { data: 'action', name: 'action', orderable: false, searchable: false },
            ],
            "{{ app()->getLocale() }}",
            "",
            jQuery('#header-buttons').html(),
            undefined,
            [[4, 'desc']]
        );
    });
</script>
@endsection