routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group([
    'middleware' => ['verified'],
    'as' => 'admin.',
    'namespace' => 'Admin',
], function() {
    Route::group(['middleware' => ['auth'], 'prefix' => 'admin'], function() {
        Route::group(['middleware' => ['active']], function() {
            /*======================================= Dashboard ==============================================*/
            Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
            /*==================================== END Dashboard ==============================================*/

            /*======================================= Profile ==============================================*/
            Route::get('profile', 'ProfileController@myProfile')->name('profile');
            Route::patch('update-profile/{id}', 'ProfileController@updateProfile')->name('profile.update');
            Route::post('update-password', 'ProfileController@updatePassword')->name('profile.updatePassword');
            /*==================================== END Profile ==============================================*/

            /*======================================= User ==============================================*/
            Route::post('users/avatar', 'UserController@avatar')->name('users.avatar');
            Route::post('users/changeStatus', 'UserController@changeStatus')->name('users.changeStatus');
            Route::post('users/data', 'UserController@data')->name('users.data');
            Route::resource('users', 'UserController');
            /*==================================== END User ==============================================*/

            /*======================================= Role ==============================================*/
            Route::post('roles/data', 'RoleController@data')->name('roles.data');
            Route::resource('roles', 'RoleController');
            /*==================================== END Role ==============================================*/

            /*======================================= Work Experience ==============================================*/
            Route::post('work-experiences/data', 'WorkExperienceController@data')->name('workExperience.data');
            Route::resource('work-experiences', 'WorkExperienceController');
            /*==================================== END Work Experience ==============================================*/

            /*======================================= Organization ==============================================*/
            Route::post('organization/data', 'OrganizationController@data')->name('organization.data');
            Route::resource('organization', 'OrganizationController');
            /*==================================== END Organization ==============================================*/
        });
    });
});

Route::group(['as' => 'user.', 'namespace' => 'User'], function() {
    Route::get('user/set-password/{code}', 'RegisterController@setPassword')->name('register.setPassword');
    Route::post('user/update-password/{id}', 'RegisterController@updatePassword')->name('register.updatePassword');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*============================================= Change Language ================================================*/
Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    app()->setLocale($locale);
    return redirect()->back();
});
/*============================================= Change Language ================================================*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/verify-email', [\App\Http\Controllers\Auth\EmailVerificationPromptController::class, '__invoke'])
    ->middleware('auth')
    ->name('verification.notice');

Route::get('/verify-email/{id}/{hash}', [\App\Http\Controllers\Auth\VerifyEmailController::class, '__invoke'])
    ->middleware(['auth', 'signed', 'throttle:6,1'])
    ->name('verification.verify');

Route::post('/email/verification-notification', [\App\Http\Controllers\Auth\EmailVerificationNotificationController::class, 'store'])
    ->middleware(['auth', 'throttle:6,1'])
    ->name('verification.send');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Mail\UserCreateMail;
use App\Models\Category;
use App\Models\Country;
use App\Models\Department;
use App\Models\User;
use App\Models\UserAuthentication;
use App\Models\UserIdentity;
use App\Models\UserVehicle;
use App\Notifications\UserCreated;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use App\Models\Role;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    public function index()
    {
        if (!auth()->user()->can('read-users')) {
            abort(401);
        }
        $roles = Role::active();
        $roles = $roles->get()->mapWithKeys(function ($value, $key) {
            return [$value->display_name => $value->name];
        })->prepend('', trans('admin_lang.select_role'));

        $user_status = [trans('admin_lang.select_status') => ''];
        foreach (User::$status as $key => $status) {
            $user_status[trans('admin_lang.status_' . $status['slug'])] = $key;
        }

        $filters = [
            User::$filter_keys['role'] => $roles,
            User::$filter_keys['status'] => $user_status
        ];
        return view('admin.users.index', compact('filters'));
    }

    //Ajax loading of data for datatables
    public function data(Request $request)
    {
        if (!auth()->user()->can('read-users')) {
            abort(401);
        }
        $users = User::with('roles');

        //apply filters if they are selected
        if ($request->has(User::$filter_keys['status']) && $request[User::$filter_keys['status']] != '') {
            $users = $users->where('status', (User::$status[strip_tags($request[User::$filter_keys['status']])]['code']) ?? '');
        }

        if ($request->has(User::$filter_keys['role']) && !empty($request[User::$filter_keys['role']])) {
            $users = $users->whereHas('roles', function ($roles) use ($request) {
                $roles->active()->where('name', strip_tags($request[User::$filter_keys['role']]));
            });
        }

        //$users = $users->where('id','!=',auth()->id());
        $users = $users->get();

        $status = [];
        //dynamic status badges from users model
        foreach (User::$status as $key => $value) {
            $status[$value['code']] = $value;
            $status[$value['code']]['key'] = $key;
        }

        return DataTables::of($users)
            ->rawColumns(['email', 'status', 'avatar'])
            ->editColumn('avatar', function ($users) {
                $html = '<div>';
                if ($users->avatar != null) {
                    $html .= '<img src="' . asset($users->avatar) . '" alt="photo" style="border-radius: 10%; width:100px">';
                } else {
                    $html .= '<span class="kt-badge kt-badge--lg kt-badge--rounded kt-badge--bold kt-font-success" style="background: rgb(0 62 249 / 16%);">' . $users->name[0] . '</span>';
                }

                $html .= '</div>';
                return $html;
            })
            ->editColumn('name', function ($users) {
                return $users->name;
            })
            ->addColumn('roles', function ($users) {
                return view('admin.users.partials.roles', with(['roles' => $users->roles]));
            })
            ->editColumn('email', function ($users) {
                return '<a href="mailto:' . $users->email . '">' . $users->email . '</a>';
            })
            ->editColumn('status', function ($users) use ($status) {
                $dropdown = 'getDropdown';
                if (auth()->id() == $users->id || $users->hasRole('admin')) {
                    $dropdown = '';
                }
                $html = '<div class="' . $dropdown . '" data-id="' . $users->id . '" style="cursor: pointer;">';
                $html .= '<a href="javascript:void(0);" data-id="' . $users->id . '"><span class="kt-badge kt-badge--inline status-' . $status[$users->status]['slug'] . '">' . trans('admin_lang.status_' . $status[$users->status]['slug']) . '</span></a>';
                $html .= '</div>';
                return $html;
            })
            ->addColumn('created', function ($users) {
                return $users->created_at->translatedFormat(config('defaults.time_format'));
            })
            ->addColumn('last_login_time', function ($users) {
                return !empty($users->last_login) ? $users->last_login->diffForHumans() : trans('admin_lang.not_yet');
            })
            ->addColumn('action', function ($users) {
                return view('admin.users.partials.actions', compact('users'));
            })
            ->make(true);
    }

    public function create()
    {
        if (!auth()->user()->can('add-users')) {
            abort(401);
        }
        $roles = Role::active()->pluck('display_name', 'id');
        return view('admin.users.create', with([
            'roles' => $roles,
        ]));
    }

    public function store(Request $request)
    {
        if (!auth()->user()->can('add-users')) {
            abort(401);
        }
        $this->__validate($request);
        try {
            $request->merge([
                'password' => Hash::make(generateRandomString(10)),
                'status' => User::$status['active']['code'],
                'created_by' => auth()->id()
            ]);
            DB::beginTransaction();
            $user = User::create($request->only(
                'first_name', 'last_name', 'email', 'password'
            ));

            $user->set_password = User::PASSWORD_NOT_SET;
            $user->status = User::$status['pending']['code'];
            $user->verification_code = generateRandomString(10);
            $user->save();

            $user->roles()->attach($request->role);

            $setPwdUrl = route('user.register.setPassword', ['code' => encrypt($user->id)]);
            $data = [
                'user' => $user,
                'setPwdUrl' => $setPwdUrl
            ];
            //Mail::to($user->email)->queue(new UserCreateMail($data));
            Notification::send($user, new UserCreated($data));

            DB::commit();
            session()->flash('success', trans('admin_lang.user_created'));
            return [
                'response' => config('response.success'),
                'redirect' => route('admin.users.index')
            ];
        } catch (\Exception $e) {
            DB::rollback();
            if (config('app.app_type') == 'local') {
                return [
                    'response' => config('response.error'),
                    'message' => $e->getMessage()
                ];
            }
            return [
                'response' => config('response.error'),
                'message' => trans('admin_lang.something'),
                'error' => $e->getMessage()
            ];
        }
    }

    public function show($user_id)
    {
        if (!auth()->user()->can('read-users')) {
            abort(401);
        }
        $user = User::with('roles')->findOrFail($user_id);
        $roles = Role::active()->get();
        return view('admin.users.show', compact('user', 'roles'));
    }

    public function edit($user_id)
    {
        if (!auth()->user()->can('edit-users')) {
            abort(401);
        }
        $user = User::with('roles')->findOrFail($user_id);

        $roles = Role::active()->get();

        return view('admin.users.edit', with([
            'user' => $user,
            'roles' => $roles,
        ]));
    }

    public function update(Request $request, $user_id)
    {
        if (!auth()->user()->can('edit-users')) {
            abort(401);
        }
        $user = User::with('roles')->findOrFail($user_id);
        $this->__validate($request, $user->id);
        try {

            $user->update($request->only(
                'first_name', 'last_name', 'email', 'status'
            ));

            if (auth()->user()->id != $user->id) {
                $user->roles()->sync($request->role);
            }
            session()->flash('success', trans('admin_lang.user_updated'));
            return [
                'response' => config('response.success'),
                'redirect' => route('admin.users.index')
            ];
        } catch (\Exception $e) {
            if (config('app.app_type') == 'local') {
                return [
                    'response' => config('response.error'),
                    'message' => $e->getMessage()
                ];
            }
            return [
                'response' => config('response.error'),
                'message' => trans('admin_lang.something')
            ];
        }
    }

    public function destroy($user_id)
    {
        if (!auth()->user()->can('delete-users')) {
            abort(401);
        }
        try {
            $user = User::findOrFail($user_id);
            $user->delete();
            return [
                'response' => config('response.success'),
                'title' => trans('admin_lang.success'),
                'message' => trans('admin_lang.user_deleted'),
                'reload' => true
            ];
        } catch (\Exception $e) {
            if (config('app.app_type') == 'local') {
                return [
                    'response' => config('response.error'),
                    'title' => trans('admin_lang.error'),
                    'message' => $e->getMessage()
                ];
            }
            return [
                'response' => config('response.error'),
                'title' => trans('admin_lang.error'),
                'message' => trans('admin_lang.something')

app/Http/Controllers/User/RegisterController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class RegisterController extends Controller
{
    public function setPassword($code){
        if(!$user = User::passwordNotSet()->whereId(decrypt($code))->first()){
            return redirect(route('login'))->with('error',trans('admin_lang.invalid_code'));
        }
        return view('admin.users.set_password',[
            'user' => $user
        ]);
    }
    public function updatePassword(Request $request,$id){
        $this->__validate($request);
        try {
            if(!$user = User::passwordNotSet()->whereId($id)->first()){
                return response()->json([
                    'response' => config('response.error'),
                    'message' => trans('admin_lang.invalid_code'),
                    'redirect' => route('login')
                ]);
            }
            DB::beginTransaction();
            $user->password = Hash::make($request->password);
            $user->status = User::$status['active']['code'];
            $user->verification_code = null;
            $user->set_password = User::PASSWORD_SET;
            $user->email_verified_at = Carbon::now();
            $user->save();

            DB::commit();
            session()->flash('success', trans('admin_lang.password_set_successfully'));
            return response()->json([
                'response' => config('response.success'),
                'redirect' => route('login')
            ]);
        } catch (\Exception $e) {
            if(config('app.app_type') == 'local'){
                return response()->json([
                    'response' => config('response.error'),
                    'message' => $e->getMessage()
                ]);
            }
            return response()->json([
                'response' => config('response.error'),
                'message' => trans('admin_lang.something')
            ]);
        }
//        return redirect(route('admin.login.index'))->with('success',trans('admin_lang.password_set_successfully'));
    }
    private function __validate(Request $request, $is_update = false)
    {

        $rules = [
            'password' => 'required|confirmed|min:8',
//            'password' => 'required|min:8',
        ];
        return $this->validate($request, $rules);
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin_main')

@section('title', trans('admin_lang.create_new_user'))

@section('content')
    <!-- begin:: Subheader -->
    @include('components.breadcrumb',[
        'home_url' => route('admin.dashboard.index'),
        'links' => [
            [
                'url' => route('admin.users.index'),
                'title' => trans('admin_lang.users_management'),
            ]
        ],
        'current_page_title' => trans('admin_lang.user_create')
    ])
    <!-- end:: Subheader -->
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="kt-portlet">
                    @include('components.header',['title' => trans('admin_lang.create_new_user'), 'icon' => 'fa fa-user-friends'])
                    <!--begin::Form-->
                    <form class="kt-form" action="{{ route('admin.users.store') }}" method="POST">
                        <div class="kt-portlet__body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="first_name" class="required">@lang('admin_lang.first_name')</label>
                                        <input id="first_name" type="text" name="first_name" placeholder="{{ trans('admin_lang.first_name_placeholder') }}" required class="form-control">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="last_name" class="required">@lang('admin_lang.last_name')</label>
                                        <input id="last_name" type="text" name="last_name" placeholder="{{ trans('admin_lang.last_name_placeholder') }}" required class="form-control">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="email" class="required">@lang('admin_lang.email')</label>
                                        <input id="email" type="email" name="email" placeholder="{{ trans('admin_lang.email_placeholder') }}" required class="form-control">
                                    </div>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="role" class="required">@lang('admin_lang.select_role')</label>
                                        <select id="role" name="role" class="form-control">
                                            <option value="">@lang('admin_lang.select_role')</option>
                                            @foreach($roles as $key => $role)
                                                <option value="{{ $key }}">{{ $role }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="kt-portlet__foot">
                            <div class="kt-form__actions">
                                @include('components.button',['type' => 'submit'])
                                @include('components.button',['type' => 'cancel', 'url' => route('admin.users.index')])
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin_main')

@section('title', trans('admin_lang.users'))

@section('content')
    @include('components.breadcrumb',[
        'home_url' => route('admin.dashboard.index'),
        'links' => [
            [
                'url' => route('admin.users.index'),
                'title' => trans('admin_lang.users_management'),
            ]
        ],
        'current_page_title' => trans('admin_lang.user_edit')
        ])
    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="kt-portlet">
                    @include('components.header',['title' => trans(('admin_lang.update_user')), 'icon' => 'fa fa-user-friends']);
                    <!--begin::Form-->
                    <form class="kt-form" action="{{ route('admin.users.update', $user->id) }}" method="PATCH">
                        <div class="kt-portlet__body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="first-name" class="required">@lang('admin_lang.first_name')</label>
                                        <input id="first-name" type="text" name="first_name" placeholder="{{ trans('admin_lang.first_name_placeholder') }}" required class="form-control" value="{{ $user->first_name }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="last-name" class="required">@lang('admin_lang.first_name')</label>
                                        <input id="last-name" type="text" name="last_name" placeholder="{{ trans('admin_lang.last_name_placeholder') }}" required class="form-control" value="{{ $user->last_name }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="email" class="required">@lang('admin_lang.email')</label>
                                        <input id="email" type="email" name="email" placeholder="{{ trans('admin_lang.email_placeholder') }}" required class="form-control" value="{{ $user->email }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="role" class="required">@lang('admin_lang.select_role')</label>
                                        <select id="role" name="role" class="form-control" {{ auth()->user()->id == $user->id ? 'disabled' : '' }}>
                                            <option value="">@lang('admin_lang.select_role')</option>
                                            @foreach($roles as $key => $role)
                                                <option value="{{ $role->id }}" {{ $user->hasRole($role->name) ? 'selected' : ''}}>{{ $role->display_name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label for="status" class="required">@lang('admin_lang.status')</label>
                                        <select id="status" name="status" class="form-control">
                                            <option value="">@lang('admin_lang.select_status')</option>
                                            @foreach(\App\Models\User::$status as $key => $status)
                                                <option value="{{ $status['code'] }}" {{ $user->status == $status['code'] ? 'selected' : ''}}>{{ trans('admin_lang.status_'.$status['slug']) }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6"></div>
                            </div>
                        </div>
                        <div class="kt-portlet__foot">
                            <div class="kt-form__actions">
                                @include('components.button',['type' => 'update'])
                                @include('components.button',['type' => 'cancel', 'url' => route('admin.users.index')])
                            </div>
                        </div>
                    </form>
                    <!--end::Form-->
                </div>
            </div>
        </div>
    </div>
@endsection

@push("scripts")
<script src="{{ asset('assets/js/pages/crud/forms/widgets/bootstrap-daterangepicker.js') }}"></script>
@endpush

resources/views/admin/users/set_password.blade.php
@extends('layouts.login_main')

@section('title', trans('admin_lang.login'))

@section('content')
    <div class="kt-grid kt-grid--hor kt-grid--root kt-login kt-login--v2 kt-login--signin" id="kt_login">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" style="background-color: white">
            <div class="kt-grid__item kt-grid__item--fluid kt-login__wrapper">
                <div class="kt-login__container">
                    <div class="kt-login__logo">
                        <a href="#">
{{--                            <img src="{{ asset('assets/media/logos/krystal_logo.png') }}">--}}
                            <h3>{{ config('app.name', 'Laravel') }}</h3>
                        </a>
                    </div>
                    <div class="kt-login__signin">
                        <div class="kt-login__head">
                            <h3 class="kt-login__title">@lang('admin_lang.set_password')</h3>
                        </div>
                        <form class="kt-form" action="{{ route('user.register.updatePassword',['id' => $user->id]) }}" method="post">
                            {{ csrf_field() }}
                            @if( Session::has('success'))
                                <div class="alert alert-success fade show" role="alert">
                                    <div class="alert-text"><strong>Success!</strong> {{ Session::get('success') }}</div>
                                    <div class="alert-close">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true"><i class="la la-close"></i></span>
                                        </button>
                                    </div>
                                </div>
                            @endif
                            @if($errors->has('email'))
                                <div class="alert alert-danger fade show" role="alert">
                                    <div class="alert-text"><strong>Error!</strong> {{ $errors->first('email') }}</div>
                                    <div class="alert-close">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true"><i class="la la-close"></i></span>
                                        </button>
                                    </div>
                                </div>
                            @endif
                            <div class="form-group">
                                <input class="form-control" type="password" placeholder="Password" name="password">
                            </div>
                            <div class="form-group">
                                <input class="form-control" type="password" placeholder="Confirm Password" name="password_confirmation">
                            </div>
                            <div class="kt-login__actions">
                                <button type="submit" class="btn btn-pill kt-login__btn-primary ajax-submit">@lang('admin_lang.continue')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection