routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group([
    'middleware' => ['verified'],
    'as' => 'admin.',
    'namespace' => 'Admin',
], function() {
    Route::group(['middleware' => ['auth'], 'prefix' => 'admin'], function() {
        Route::group(['middleware' => ['active']], function() {
            /*======================================= Dashboard ==============================================*/
            Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
            /*==================================== END Dashboard ==============================================*/

            /*======================================= Profile ==============================================*/
            Route::get('profile', 'ProfileController@myProfile')->name('profile');
            Route::patch('update-profile/{id}', 'ProfileController@updateProfile')->name('profile.update');
            Route::post('update-password', 'ProfileController@updatePassword')->name('profile.updatePassword');
            /*==================================== END Profile ==============================================*/

            /*======================================= User ==============================================*/
            Route::post('users/avatar', 'UserController@avatar')->name('users.avatar');
            Route::post('users/changeStatus', 'UserController@changeStatus')->name('users.changeStatus');
            Route::post('users/data', 'UserController@data')->name('users.data');
            Route::resource('users', 'UserController');
            /*==================================== END User ==============================================*/

            /*======================================= Role ==============================================*/
            Route::post('roles/data', 'RoleController@data')->name('roles.data');
            Route::resource('roles', 'RoleController');
            /*==================================== END Role ==============================================*/

            /*======================================= Work Experience ==============================================*/
            Route::post('work-experiences/data', 'WorkExperienceController@data')->name('workExperience.data');
            Route::resource('work-experiences', 'WorkExperienceController');
            /*==================================== END Work Experience ==============================================*/

            /*======================================= Organization ==============================================*/
            Route::post('organization/data', 'OrganizationController@data')->name('organization.data');
            Route::resource('organization', 'OrganizationController');
            /*==================================== END Organization ==============================================*/
        });
    });
});

Route::group(['as' => 'user.', 'namespace' => 'User'], function() {
    Route::get('user/set-password/{code}', 'RegisterController@setPassword')->name('register.setPassword');
    Route::post('user/update-password/{id}', 'RegisterController@updatePassword')->name('register.updatePassword');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*============================================= Change Language ================================================*/
Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    app()->setLocale($locale);
    return redirect()->back();
});
/*============================================= Change Language ================================================*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/verify-email', [\App\Http\Controllers\Auth\EmailVerificationPromptController::class, '__invoke'])
    ->middleware('auth')
    ->name('verification.notice');

Route::get('/verify-email/{id}/{hash}', [\App\Http\Controllers\Auth\VerifyEmailController::class, '__invoke'])
    ->middleware(['auth', 'signed', 'throttle:6,1'])
    ->name('verification.verify');

Route::post('/email/verification-notification', [\App\Http\Controllers\Auth\EmailVerificationNotificationController::class, 'store'])
    ->middleware(['auth', 'throttle:6,1'])
    ->name('verification.send');

resources/views/layouts/admin_main.blade.php
<!DOCTYPE html>
@if(app()->getLocale() == 'ar')
    <html direction="rtl" dir="rtl" style="direction: rtl">
@else
    <html>
@endif
<!-- <html direction="rtl" dir="rtl" style="direction: rtl" > -->
<!-- begin::Head -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
    <meta charset="utf-8"/>
    <title>@yield('title') | @lang('admin_lang.admin')</title>
    <meta name="description" content="Page with empty content">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!--begin::Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">
    <!--end::Fonts -->
    <!--begin::Page Vendors Styles(used by this page) -->
{{--    <link href="{{ asset('assets/plugins/custom/fullcalendar/fullcalendar.bundle.css') }}" rel="stylesheet" type="text/css" />--}}
    <!--end::Page Vendors Styles -->
    <!--begin::Global Theme Styles(used by all pages) -->
    <link href="{{ asset('assets/plugins/global/plugins.bundle.css') }}" rel="stylesheet" type="text/css" />
    @if(app()->getLocale() == 'ar')
        <link title ='en' href="{{ asset('assets/css/style.bundle.rtl.css') }}" rel="stylesheet" type="text/css" />
        <link title ='en' href="{{ asset('assets/css/custom.style.rtl.css') }}" rel="stylesheet" type="text/css" />
    @else
        <link title ='en' href="{{ asset('assets/css/style.bundle.css') }}" rel="stylesheet" type="text/css" />
    @endif
    <!--end::Global Theme Styles -->
    <!--begin::Layout Skins(used by all pages) -->

    <link href="{{ asset('assets/css/skins/header/base/light.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/css/skins/header/menu/light.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/css/skins/brand/dark.css') }}" rel="stylesheet" type="text/css" />
    <link href="https://cdn.rawgit.com/filamentgroup/fixed-sticky/master/fixedsticky.css" rel="stylesheet" type="text/css" />
    <!-- <link href="{{ asset('assets/css/skins/aside/dark.css') }}" rel="stylesheet" type="text/css" /> -->
    <link href="{{asset('css/loader.css')}}" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="{{ asset('assets/media/logos/fav-icon-2.png') }}" />
    <link href="{{ url('css/style.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{asset('css/custom.css')}}" rel="stylesheet" type="text/css" />
    <style type="text/css">
        #kt_subheader + .kt-container,
        #kt_subheader + .order_detail_section,
        #kt_subheader + .kt-portlet {
            margin-top: 50px;
        }

        table.table-bordered.dataTable tbody th,
        .dataTables_wrapper .dataTable thead tr th {
            white-space: nowrap;
        }

        table [title] {
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
            width: 6rem;
            display: block;
        }
    </style>
    @yield('head-js')
    @yield('css')
    @stack('styles')
</head>
<!-- end::Head -->
<!-- begin::Body -->
<body  class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--fixed kt-subheader--solid kt-aside--enabled kt-aside--fixed kt-page--loading"  >
    <div class="loading" style="display: none;">Loading&#8230;</div>
    <!-- begin:: Page -->
    <!-- begin:: Header Mobile -->
    <div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed " >
        <div class="kt-header-mobile__logo">
            <a href="javascript:void(0);"> <img alt="Logo" src="{{ asset('assets/media/logos/logo-light.png') }}"/> </a>
        </div>
        <div class="kt-header-mobile__toolbar">
            <button class="kt-header-mobile__toggler kt-header-mobile__toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
        </div>
    </div>
    <!-- end:: Header Mobile -->
    <div class="kt-grid kt-grid--hor kt-grid--root">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">
            <!-- begin:: Aside -->
            <!-- Uncomment this to display the close button of the panel -->
            <button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
            <div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">
                <!-- begin:: Aside -->
                <div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
                    <div class="kt-aside__brand-logo"style="padding: 0 25px 0 0">
                        {{--<a href="javascript:void(0);"> <img alt="Logo" src="{{ asset('assets/media/logos/logo-light.png') }}"/> </a>--}}
                    </div>
                    <div class="kt-aside__brand-tools">
                        <button class="kt-aside__brand-aside-toggler" id="kt_aside_toggler" style="color: #83162c;">
                            <span>
                                <i class="fa fa-2x fa-angle-double-left"></i>
                            </span>
                            <span>
                                <i class="fa fa-2x fa-angle-double-right"></i>
                            </span>
                        </button>
                    </div>
                </div>
                <!-- end:: Aside -->
                @include('layouts.sidebar')
            </div>
            <!-- end:: Aside -->
            <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper" style="padding-top: 50px;">
                <!-- begin:: Header -->
                <div id="kt_header" class="kt-header kt-grid__item  kt-header--fixed" >
                    @include('layouts.header')
                </div>
                <!-- end:: Header -->
                <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
                    <!-- begin:: Content -->
                    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
                        @yield('content')
                    </div>
                    <!-- end:: Content -->
                </div>
                <!-- begin:: Footer -->
                <div class="kt-footer  kt-grid__item kt-grid kt-grid--desktop kt-grid--ver-desktop" id="kt_footer">
                    <div class="kt-container  kt-container--fluid ">
                        <div class="kt-footer__copyright">
                            <?php echo date(
                                'Y'
                            ); ?>&nbsp;&copy;&nbsp;@lang('admin_lang.app_name')
                        </div>
                    </div>
                </div>
                <!-- end:: Footer -->
            </div>
        </div>
    </div>
    <!-- end:: Page -->
    <!-- begin::Quick Panel -->
    <div id="kt_quick_panel" class="kt-quick-panel">
        <a href="#" class="kt-quick-panel__close" id="kt_quick_panel_close_btn"><i class="flaticon2-delete"></i></a>
        <div class="kt-quick-panel__nav">
            <ul class="nav nav-tabs nav-tabs-line nav-tabs-bold nav-tabs-line-3x nav-tabs-line-brand  kt-notification-item-padding-x" role="tablist">
                <li class="nav-item active">
                    <a class="nav-link active" data-toggle="tab" href="#kt_quick_panel_tab_notifications" role="tab">Notifications</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#kt_quick_panel_tab_logs" role="tab">Audit Logs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#kt_quick_panel_tab_settings" role="tab">Settings</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- end::Quick Panel -->
    <!-- begin::Scrolltop -->
    <div id="kt_scrolltop" class="kt-scrolltop">
        <i class="fa fa-arrow-up"></i>
    </div>
    <!-- begin::Global Config(global config for global JS sciprts) -->
    <script>
        var en_css_url = "{{ asset('assets/css/style.bundle.rtl.css') }}";
        var en_customCss_url = "{{ asset('assets/css/custom.style.rtl.css') }}";

        var KTAppOptions = {
            "colors": {
                "state": {
                    "brand": "#5d78ff",
                    "dark": "#282a3c",
                    "light": "#ffffff",
                    "primary": "#5867dd",
                    "success": "#34bfa3",
                    "info": "#36a3f7",
                    "warning": "#ffb822",
                    "danger": "#fd3995"
                },
                "base": {
                    "label": [
                        "#c5cbe3",
                        "#a1a8c3",
                        "#3d4465",
                        "#3e4466"
                    ],
                    "shape": [
                        "#f0f3ff",
                        "#d9dffa",
                        "#afb4d4",
                        "#646c9a"
                    ]
                }
            }
        };
    </script>
    <!-- end::Global Config -->
    <!--begin::Global Theme Bundle(used by all pages) -->
    <script src="{{ asset('assets/plugins/global/plugins.bundle.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/scripts.bundle.js') }}" type="text/javascript"></script>

    <script src="https://cdn.rawgit.com/filamentgroup/fixed-sticky/master/fixedsticky.js"></script>
    <script src="{{ asset('assets/js/custom.js') }}"></script>
    <script src="{{ asset('assets/js/pages/components/extended/toastr.js') }}" type="text/javascript"></script>

    <script>
          $( '.map_block' ).fixedsticky();
            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": false,
                "progressBar": true,
                "positionClass": "toast-top-center",
                "preventDuplicates": true,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            };
        /** loading overlay start */
        function showLoading() {
            $('.loading').css('display', 'block');
        }

        function hideLoading() {
            $('.loading').css('display', 'none');
        }

        /** loading overlay end */

        $('textarea').each(function () {
                $(this).val($(this).val().trim());
            }
        );

        @if(session('success'))
            toastr.success("{!! session('success') !!}", "{!! trans('admin_lang.success') !!}");
        @endif
        @if(session('warning'))
            toastr.warning("{!! session('warning') !!}", "{!! trans('admin_lang.warning') !!}");
        @endif
        @if(session('error'))
            toastr.error("{!! session('error') !!}", "{!! trans('admin_lang.error') !!}");
        @endif
        function successToast(msg) {
            toastr.success(msg, "{!! trans('admin_lang.success') !!}");
        }
        function errorToast(msg) {
            toastr.error(msg, "{!! trans('admin_lang.error') !!}");
        }
        function warningToast(msg) {
            toastr.warning(msg, "{!! trans('admin_lang.error') !!}");
        }
    </script>
    <!--end::Page Scripts -->
    <script type="text/javascript">
        $(document).ready(function(){
            var csrfToken = '{!! csrf_token() !!}';
        });

        $( document ).ready(function() {
            $('#timezone').val(new Date().getTimezoneOffset());
        });
    </script>
    @yield('js')
    @stack('scripts')
</body>
<!-- end::Body -->
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<!-- begin:: Header Menu -->
{{--Uncomment this to display the close button of the panel--}}
{{--<button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>--}}

<div class=" container-fluid  d-flex align-items-stretch justify-content-between">
    <!-- end:: Header Menu -->
    <div class="header-menu-wrapper header-menu-wrapper-left">
        <div class="store_name">
                {{--<a href="{{ '/' }}">--}}
                    {{--<span class="svg-icon svg-icon-2x"><!--begin::Svg Icon | path:/home/keenthemes/www/metronic/themes/metronic/theme/html/demo1/dist/../src/media/svg/icons/Home/Home.svg-->--}}
                        {{--<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">--}}
                            {{--<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">--}}
                                {{--<rect x="0" y="0" width="24" height="24"/>--}}
                                {{--<path d="M13.5,21 L13.5,18 C13.5,17.4477153 13.0522847,17 12.5,17 L11.5,17 C10.9477153,17 10.5,17.4477153 10.5,18 L10.5,21 L5,21 L5,4 C5,2.8954305 5.8954305,2 7,2 L17,2 C18.1045695,2 19,2.8954305 19,4 L19,21 L13.5,21 Z M9,4 C8.44771525,4 8,4.44771525 8,5 L8,6 C8,6.55228475 8.44771525,7 9,7 L10,7 C10.5522847,7 11,6.55228475 11,6 L11,5 C11,4.44771525 10.5522847,4 10,4 L9,4 Z M14,4 C13.4477153,4 13,4.44771525 13,5 L13,6 C13,6.55228475 13.4477153,7 14,7 L15,7 C15.5522847,7 16,6.55228475 16,6 L16,5 C16,4.44771525 15.5522847,4 15,4 L14,4 Z M9,8 C8.44771525,8 8,8.44771525 8,9 L8,10 C8,10.5522847 8.44771525,11 9,11 L10,11 C10.5522847,11 11,10.5522847 11,10 L11,9 C11,8.44771525 10.5522847,8 10,8 L9,8 Z M9,12 C8.44771525,12 8,12.4477153 8,13 L8,14 C8,14.5522847 8.44771525,15 9,15 L10,15 C10.5522847,15 11,14.5522847 11,14 L11,13 C11,12.4477153 10.5522847,12 10,12 L9,12 Z M14,12 C13.4477153,12 13,12.4477153 13,13 L13,14 C13,14.5522847 13.4477153,15 14,15 L15,15 C15.5522847,15 16,14.5522847 16,14 L16,13 C16,12.4477153 15.5522847,12 15,12 L14,12 Z" fill="#000000"/>--}}
                                {{--<rect fill="#FFFFFF" x="13" y="8" width="3" height="3" rx="1"/>--}}
                                {{--<path d="M4,21 L20,21 C20.5522847,21 21,21.4477153 21,22 L21,22.4 C21,22.7313708 20.7313708,23 20.4,23 L3.6,23 C3.26862915,23 3,22.7313708 3,22.4 L3,22 C3,21.4477153 3.44771525,21 4,21 Z" fill="#000000" opacity="0.3"/>--}}
                            {{--</g>--}}
                        {{--</svg>--}}
                    {{--</span>--}}
                    {{--<span class="st_label">{{ trans('admin_lang.company') }}:</span>--}}
                    {{--<span class="st_name">{{ 'Test Company' }}</span>--}}
                    {{--@lang('admin_lang.change_company')--}}
                {{--</a>--}}
            </div>
    </div>
    <!-- begin:: Header Topbar -->
    <div class="kt-header__topbar">

        <!--begin: User Bar -->
        <div class="kt-header__topbar-item kt-header__topbar-item--user show">
            <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="0px,0px" aria-expanded="true">
                <div class="kt-header__topbar-user">
                    <span class="kt-header__topbar-welcome kt-hidden-mobile">@lang('admin_lang.hi'),</span>
                    <span class="kt-header__topbar-username kt-hidden-mobile">{{ auth()->user()->name }}</span>
                    @php($default_url = asset('/images/user-hero.png'))
                    <div class="at_profile">
                        <img src="{{ $default_url }}" onerror="this.src='{{ $default_url }}'" alt="{{ auth()->check() ? auth()->user()->name : 'Guest' }}">
                    </div>
                    <i class="kt-menu__ver-arrow la la-angle-down"></i>
                    {{--<span class="kt-badge kt-badge--username kt-badge--unified-success kt-badge--lg kt-badge--rounded kt-badge--bold">S</span>--}}
                </div>
            </div>

            <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-top-unround dropdown-menu-xl" style="width:25%;">
                <!--begin: Head -->
                <div class="kt-user-card kt-user-card--skin-dark kt-notification-item-padding-x" style="background-image: url('{{ asset('assets/media/misc/bg-1.jpg') }}')">
                    <div class="kt-user-card__avatar">
                        @if(auth()->user()->avatar != null)
                            <img alt="avatar" src="{{ asset(auth()->user()->avatar) }}">
                        @else
                            <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
                            <span class="kt-badge kt-badge--lg kt-badge--rounded kt-badge--bold kt-font-success">{{ ucwords(auth()->user()->name[0]) }}</span>
                        @endif
                    </div>
                    <div class="kt-user-card__name">
                        {{ auth()->user()->name }}
                    </div>
                </div>
                <!--end: Head -->

                <!--begin: Navigation -->
                <div class="kt-notification">
                    <a href="{{ route('admin.profile') }}" class="kt-notification__item">
                        <div class="kt-notification__item-icon">
                            <i class="flaticon2-calendar-3 kt-font-success"></i>
                        </div>
                        <div class="kt-notification__item-details">
                            <div class="kt-notification__item-title kt-font-bold">
                                @lang('admin_lang.my_profile')
                            </div>
                            <div class="kt-notification__item-time">
                                @lang('admin_lang.account_settings')
                            </div>
                        </div>
                    </a>
                    <div class="kt-notification__custom kt-space-between" style="padding: 15px;">
                        <form action="{{ route('logout') }}" method="post" style="margin: 0;">
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-label btn-label-brand btn-sm btn-bold" style="width: 150%">@lang('admin_lang.signOut')</button>
                        </form>
                    </div>
                </div>
                <!--end: Navigation -->
            </div>
        </div>
        <!--end: User Bar -->
    </div>
    <!-- end:: Header Topbar -->
</div>

resources/views/layouts/sidebar.blade.php
<!-- begin:: Aside Menu -->
<div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
    <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1"
         data-ktmenu-dropdown-timeout="500">
        <ul class="kt-menu__nav ">
            <li class="kt-menu__item " aria-haspopup="true">
                <a href="{{ route('admin.dashboard.index') }}" class="kt-menu__link {{ Request::is( 'admin/dashboard')  ? 'active' : '' }}">
                    <span class="kt-menu__link-icon">
                        <i class="fa fa-tachometer-alt"></i>
                    </span>
                    <span class="kt-menu__link-text">
                        @lang('admin_lang.module_dashboard')
                    </span>
                </a>
            </li>
            <li class="kt-menu__item " aria-haspopup="true">
                <a href="{{ route('admin.profile') }}" class="kt-menu__link {{ Request::is( 'admin/profile')  ? 'active' : '' }}">
                    <span class="kt-menu__link-icon">
                        <i class="fas fa-address-card"></i>
                    </span>
                    <span class="kt-menu__link-text">
                        @lang('admin_lang.my_profile')
                    </span>
                </a>
            </li>

            @if(hasPermissionWithActiveRole('read-users', auth()->user()))
                <li class="kt-menu__item " aria-haspopup="true">
                    <a href="{{ route('admin.users.index') }}" class="kt-menu__link {{ Request::is( 'admin/users*')  ? 'active' : '' }}">
                        <span class="kt-menu__link-icon user_icon_aside">
                            <i class="fa fa-user-friends"></i>
                        </span>
                        <span class="kt-menu__link-text">@lang('admin_lang.module_users')</span>
                    </a>
                </li>
            @endif

            @if(hasPermissionWithActiveRole('read-roles', auth()->user()))
                <li class="kt-menu__item " aria-haspopup="true">
                    <a href="{{ route('admin.roles.index')  }}" class="kt-menu__link {{ Request::is( 'admin/roles*')  ? 'active' : '' }}">
                        <span class="kt-menu__link-icon user_icon_aside">
                            <i class="fa fa-user-tie"></i>
                        </span>
                        <span class="kt-menu__link-text">@lang('admin_lang.module_roles')</span>
                    </a>
                </li>
            @endif
            <li class="kt-menu__item " aria-haspopup="true">
                <a href="{{ route('admin.work-experiences.index') }}" class="kt-menu__link {{ Request::is( 'admin/work-experiences*')  ? 'active' : '' }}">
                        <span class="kt-menu__link-icon user_icon_aside">
                            <i class="fas fa-hotel"></i>
                        </span>
                    <span class="kt-menu__link-text">@lang('admin_lang.work_experience')</span>
                </a>
            </li>
            <li class="kt-menu__item " aria-haspopup="true">
                <a href="{{ route('admin.organization.index') }}" class="kt-menu__link {{ Request::is( 'admin/organization*')  ? 'active' : '' }}">
                        <span class="kt-menu__link-icon user_icon_aside">
                            <i class="far fa-building"></i>
                        </span>
                    <span class="kt-menu__link-text">@lang('admin_lang.organization')</span>
                </a>
            </li>

        </ul>
    </div>
</div>
<!-- end:: Aside Menu -->